
SwatterData = {
	["enabled"] = true,
	["warning"] = true,
	["combat"] = false,
	["errors"] = {
		{
			["message"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: attempt to call global 'GetPrimaryTalentTree' (a nil value)",
			["count"] = 2,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  BGSpy, v1.2.6\n  BigWigs, v4.360\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SatrinaBuffFrame, v3.2\n  SexyMap, v2.4.9\n  ShadowedUnitFrames, vv3.8.10\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TidyPlates, v6.12.3\n  TidyPlatesGraphite, v\n  TidyPlatesGrey, v\n  TidyPlatesNeon, v\n  TidyPlatesQuatre, v\n  TidyPlatesHub, v\n  TidyPlatesWidgets, v\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlOptions, v\n  XPerlParty, v\n  XPerlPartyPet, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidAdmin, v\n  XPerlRaidFrames, v\n  XPerlRaidHelper, v\n  XPerlRaidPets, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=4c6)\n",
			["locals"] = "(*temporary) = nil\n(*temporary) = \"attempt to call global 'GetPrimaryTalentTree' (a nil value)\"\nArmorSpecActive = nil\npairs = <function> defined =[C]:-1\nWatchInventoryID = <table> {\n 1 = 1\n 2 = 3\n 3 = 5\n 4 = 9\n 5 = 10\n 6 = 6\n 7 = 7\n 8 = 8\n}\nGetInventoryItemID = <function> defined =[C]:-1\nselect = <function> defined =[C]:-1\nGetItemInfo = <function> defined @Interface\\AddOns\\RatingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:5874\nplayerArmorType = \"Leather\"\n",
			["timestamp"] = "2013-09-17 17:17:34",
			["context"] = "Global",
			["stack"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6516>\n...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6530: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6527>\n",
		}, -- [1]
		{
			["message"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: attempt to call global 'GetPrimaryTalentTree' (a nil value)",
			["count"] = 5,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  BigWigs, v4.360\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SatrinaBuffFrame, v3.2\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TidyPlates, v6.12.3\n  TidyPlatesGraphite, v\n  TidyPlatesGrey, v\n  TidyPlatesNeon, v\n  TidyPlatesQuatre, v\n  TidyPlatesHub, v\n  TidyPlatesWidgets, v\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlParty, v\n  XPerlPartyPet, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidAdmin, v\n  XPerlRaidFrames, v\n  XPerlRaidHelper, v\n  XPerlRaidPets, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=485)\n",
			["locals"] = "(*temporary) = nil\n(*temporary) = \"attempt to call global 'GetPrimaryTalentTree' (a nil value)\"\nArmorSpecActive = nil\npairs = <function> defined =[C]:-1\nWatchInventoryID = <table> {\n 1 = 1\n 2 = 3\n 3 = 5\n 4 = 9\n 5 = 10\n 6 = 6\n 7 = 7\n 8 = 8\n}\nGetInventoryItemID = <function> defined =[C]:-1\nselect = <function> defined =[C]:-1\nGetItemInfo = <function> defined @Interface\\AddOns\\RatingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:5874\nplayerArmorType = \"Leather\"\n",
			["timestamp"] = "2013-09-17 17:27:05",
			["context"] = "Global",
			["stack"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6516>\n...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6548: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6547>\n(tail call): ?\n",
		}, -- [2]
		{
			["message"] = "Note: AddOn XPerl_RaidFrames attempted to call a protected function (UNKNOWN()) during combat lockdown.",
			["count"] = 1,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  BigWigs, v4.360\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  DBMPandaria, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SatrinaBuffFrame, v3.2\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TidyPlates, v6.12.3\n  TidyPlatesGraphite, v\n  TidyPlatesGrey, v\n  TidyPlatesNeon, v\n  TidyPlatesQuatre, v\n  TidyPlatesHub, v\n  TidyPlatesWidgets, v\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlParty, v\n  XPerlPartyPet, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidAdmin, v\n  XPerlRaidFrames, v\n  XPerlRaidHelper, v\n  XPerlRaidPets, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=496)\n",
			["timestamp"] = "2013-09-17 17:30:17",
			["context"] = "AddOn: XPerl_RaidFrames",
			["stack"] = "[C]: ?\n[C]: in function `CreateFrame'\nInterface\\FrameXML\\SecureGroupHeaders.lua:164: in function <Interface\\FrameXML\\SecureGroupHeaders.lua:123>\nInterface\\FrameXML\\SecureGroupHeaders.lua:488: in function `SecureGroupHeader_Update'\nInterface\\FrameXML\\SecureGroupHeaders.lua:62: in function <Interface\\FrameXML\\SecureGroupHeaders.lua:60>\n",
		}, -- [3]
		{
			["message"] = "Note: AddOn XPerl_RaidPets attempted to call a protected function (UNKNOWN()) during combat lockdown.",
			["count"] = 1,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  BigWigs, v4.360\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  DBMPandaria, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SatrinaBuffFrame, v3.2\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TidyPlates, v6.12.3\n  TidyPlatesGraphite, v\n  TidyPlatesGrey, v\n  TidyPlatesNeon, v\n  TidyPlatesQuatre, v\n  TidyPlatesHub, v\n  TidyPlatesWidgets, v\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlParty, v\n  XPerlPartyPet, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidAdmin, v\n  XPerlRaidFrames, v\n  XPerlRaidHelper, v\n  XPerlRaidPets, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=496)\n",
			["timestamp"] = "2013-09-17 17:33:18",
			["context"] = "AddOn: XPerl_RaidPets",
			["stack"] = "[C]: ?\n[C]: in function `CreateFrame'\nInterface\\FrameXML\\SecureGroupHeaders.lua:164: in function <Interface\\FrameXML\\SecureGroupHeaders.lua:123>\nInterface\\FrameXML\\SecureGroupHeaders.lua:623: in function `SecureGroupPetHeader_Update'\nInterface\\FrameXML\\SecureGroupHeaders.lua:507: in function <Interface\\FrameXML\\SecureGroupHeaders.lua:505>\n",
		}, -- [4]
		{
			["message"] = "Usage: GameTooltip:SetUnitAura(\"unit\", [index] or [\"name\", \"rank\"][, \"filter\"])",
			["count"] = 4,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  BigWigs, v4.360\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  DBMPandaria, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SatrinaBuffFrame, v3.2\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TidyPlates, v6.12.3\n  TidyPlatesGraphite, v\n  TidyPlatesGrey, v\n  TidyPlatesNeon, v\n  TidyPlatesQuatre, v\n  TidyPlatesHub, v\n  TidyPlatesWidgets, v\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlParty, v\n  XPerlPartyPet, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidAdmin, v\n  XPerlRaidFrames, v\n  XPerlRaidHelper, v\n  XPerlRaidPets, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=496)\n",
			["locals"] = "(*temporary) = GameTooltip {\n 0 = <userdata>\n SetText = <function> defined @Interface\\AddOns\\Gatherer\\Swag\\LibSwag.lua:408\n SetExistingSocketGem = <function> defined =[C]:-1\n SetCurrencyToken = <function> defined =[C]:-1\n SetGuildBankItem = <function> defined =[C]:-1\n hasMoney = 1\n ClearLines = <function> defined @Interface\\AddOns\\Gatherer\\Swag\\LibSwag.lua:417\n SetSocketGem = <function> defined =[C]:-1\n SetUnitDebuff = <function> defined =[C]:-1\n SetLootItem = <function> defined =[C]:-1\n SetQuestItem = <function> defined =[C]:-1\n SetReforgeItem = <function> defined =[C]:-1\n SetTrainerService = <function> defined =[C]:-1\n numMoneyFrames = 1\n SetInboxItem = <function> defined =[C]:-1\n SetBuybackItem = <function> defined =[C]:-1\n shoppingTooltips = <table> {\n }\n SetHyperlinkCompareItem = <function> defined =[C]:-1\n SetMerchantItem = <function> defined =[C]:-1\n SetQuestLogItem = <function> defined =[C]:-1\n SetBackpackToken = <function> defined =[C]:-1\n SetTradeTargetItem = <function> defined =[C]:-1\n SetTradePlayerItem = <function> defined =[C]:-1\n SetSendMailItem = <function> defined =[C]:-1\n updateTooltip = 0.070999993756413\n SetInventoryItem = <function> defined =[C]:-1\n comparing = false\n SetLootRollItem = <function> defined =[C]:-1\n SetUnitAura = <function> defined =[C]:-1\n tfade = <unnamed> {\n }\n SetAuctionSellItem = <function> defined =[C]:-1\n SetBagItem = <function> defined =[C]:-1\n SetUnitBuff = <function> defined =[C]:-1\n SetHyperlink = <function> defined =[C]:-1\n SetTradeSkillItem = <function> defined =[C]:-1\n SetMerchantCostItem = <function> defined =[C]:-1\n SetAuctionItem = <function> defined =[C]:-1\n}\n(*temporary) = \"Player\"\n(*temporary) = nil\n(*temporary) = nil\n",
			["timestamp"] = "2013-09-17 17:34:59",
			["context"] = "Global",
			["stack"] = "[C]: ?\n[C]: in function `SetUnitAura'\nInterface\\AddOns\\SatrinaBuffFrame\\SBFElements.lua:872: in function <Interface\\AddOns\\SatrinaBuffFrame\\SBFElements.lua:852>\n",
		}, -- [5]
		{
			["message"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: attempt to call global 'GetPrimaryTalentTree' (a nil value)",
			["count"] = 2,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  BigWigs, v4.360\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SatrinaBuffFrame, v3.2\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TidyPlates, v6.12.3\n  TidyPlatesGraphite, v\n  TidyPlatesGrey, v\n  TidyPlatesNeon, v\n  TidyPlatesQuatre, v\n  TidyPlatesHub, v\n  TidyPlatesWidgets, v\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlParty, v\n  XPerlPartyPet, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidAdmin, v\n  XPerlRaidFrames, v\n  XPerlRaidHelper, v\n  XPerlRaidPets, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=485)\n",
			["locals"] = "(*temporary) = nil\n(*temporary) = \"attempt to call global 'GetPrimaryTalentTree' (a nil value)\"\nArmorSpecActive = nil\npairs = <function> defined =[C]:-1\nWatchInventoryID = <table> {\n 1 = 1\n 2 = 3\n 3 = 5\n 4 = 9\n 5 = 10\n 6 = 6\n 7 = 7\n 8 = 8\n}\nGetInventoryItemID = <function> defined =[C]:-1\nselect = <function> defined =[C]:-1\nGetItemInfo = <function> defined @Interface\\AddOns\\RatingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:5874\nplayerArmorType = \"Leather\"\n",
			["timestamp"] = "2013-09-17 17:57:45",
			["context"] = "Global",
			["stack"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6516>\n...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6530: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6527>\n",
		}, -- [6]
		{
			["message"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: attempt to call global 'GetPrimaryTalentTree' (a nil value)",
			["count"] = 2,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidAdmin, v\n  XPerlRaidFrames, v\n  XPerlRaidHelper, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=38e)\n",
			["locals"] = "(*temporary) = nil\n(*temporary) = \"attempt to call global 'GetPrimaryTalentTree' (a nil value)\"\nArmorSpecActive = nil\npairs = <function> defined =[C]:-1\nWatchInventoryID = <table> {\n 1 = 1\n 2 = 3\n 3 = 5\n 4 = 9\n 5 = 10\n 6 = 6\n 7 = 7\n 8 = 8\n}\nGetInventoryItemID = <function> defined =[C]:-1\nselect = <function> defined =[C]:-1\nGetItemInfo = <function> defined @Interface\\AddOns\\RatingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:5874\nplayerArmorType = \"Leather\"\n",
			["timestamp"] = "2013-09-17 18:06:51",
			["context"] = "Global",
			["stack"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6516>\n...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6548: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6547>\n(tail call): ?\n",
		}, -- [7]
		{
			["message"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: attempt to call global 'GetPrimaryTalentTree' (a nil value)",
			["count"] = 9,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidHelper, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=365)\n",
			["locals"] = "(*temporary) = nil\n(*temporary) = \"attempt to call global 'GetPrimaryTalentTree' (a nil value)\"\nArmorSpecActive = nil\npairs = <function> defined =[C]:-1\nWatchInventoryID = <table> {\n 1 = 1\n 2 = 3\n 3 = 5\n 4 = 9\n 5 = 10\n 6 = 6\n 7 = 7\n 8 = 8\n}\nGetInventoryItemID = <function> defined =[C]:-1\nselect = <function> defined =[C]:-1\nGetItemInfo = <function> defined @Interface\\AddOns\\RatingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:5874\nplayerArmorType = \"Leather\"\n",
			["timestamp"] = "2013-09-17 18:07:20",
			["context"] = "Global",
			["stack"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6516>\n...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6548: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6547>\n(tail call): ?\n",
		}, -- [8]
		{
			["message"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: attempt to call global 'GetPrimaryTalentTree' (a nil value)",
			["count"] = 1,
			["addons"] = "  Swatter, v4.4.0 (<%codename%>)\n  ACP, v3.4.4 \n  AtlasLootLoader, vv7.07.00\n  Babylonian, v5.1.DEV.332(/embedded)\n  BadBoy, v12.042\n  BagBrother, v\n  Bagnon, v5.4.2\n  Bartender4, v4.5.13\n  Configator, v5.1.DEV.344(/embedded)\n  DBMCore, v\n  epgp, v5.9.16\n  epgplootmaster, v0.6.34\n  epgplootmasterml, v0.6.34\n  Gatherer, v4.4.0\n  GatherMate2, v1.27\n  Grid, v5.3.0.1621\n  GridStatusRaidDebuff, v5.41\n  Mapster, v1.5.5\n  Omen, v3.1.8\n  OmniCC, v5.4.0\n  Postal, v3.5.1\n  Quartz, v3.1.3\n  RatingBuster, v1.6.7\n  Recount, v\n  SexyMap, v2.4.9\n  Skinner, vb5.17539.1\n  SlideBar, v4.4.0 (<%codename%>)\n  TrickOrTreat, v\n  WeakAuras, v1.4.7.10\n  XPerl, v3.7.3\n  XPerlArcaneBar, v\n  XPerlPlayer, v\n  XPerlPlayerBuffs, v\n  XPerlPlayerPet, v\n  XPerlRaidHelper, v\n  XPerlTarget, v\n  XPerlTargetTarget, v\n  YorsahjAutomaticRaidwarnings, v1.2f\n  BlizRuntimeLib_enUS v5.4.0.50400 <us>\n  (ck=365)\n",
			["locals"] = "(*temporary) = nil\n(*temporary) = \"attempt to call global 'GetPrimaryTalentTree' (a nil value)\"\nArmorSpecActive = nil\npairs = <function> defined =[C]:-1\nWatchInventoryID = <table> {\n 1 = 1\n 2 = 3\n 3 = 5\n 4 = 9\n 5 = 10\n 6 = 6\n 7 = 7\n 8 = 8\n}\nGetInventoryItemID = <function> defined =[C]:-1\nselect = <function> defined =[C]:-1\nGetItemInfo = <function> defined @Interface\\AddOns\\RatingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:5874\nplayerArmorType = \"Leather\"\n",
			["timestamp"] = "2013-09-17 20:41:02",
			["context"] = "Global",
			["stack"] = "...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6524: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6516>\n...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6530: in function <...ingBuster\\libs\\LibStatLogic-1.2\\LibStatLogic-1.2.lua:6527>\n",
		}, -- [9]
	},
	["autoshow"] = true,
}
